#pragma once

enum class EMinoType : __int8
{
	I_MINO,
	O_MINO,
	T_MINO,
	J_MINO,
	L_MINO,
	S_MINO,
	Z_MINO,
	MAX
};

enum class EZOrder
{
	NONE = 1,
	KNIGHT_SKILL_FIREBALL_ATTACK_EFFECT = 100,
	KNIGHT_SKILL_SLASK_EFFECT = 110,
	KNIGHT_SKILL_FIREBALL_EFFECT = 120,
	KNIGHT_SKILL_FRONT = 200,
	HitParticleEffect = 400,
	HIT_LIGHT_EFFECT = 700,
	BARRIER = 750,
	PLAYER = 800,
	KNIGHT_STUN_EFFECT = 850,
	MONSTER_SKILL_FRONT = 1000,
	MONSTER = 1100,
	KNIGHT_SKILL_BACK = 1200,
	MONSTER_SKILL_BACK = 1300,
	BACKGROUND = 1500,
	PIXELCOLLISION = 3999,
	MAX_ZORDER
};

enum class ETypeInfo
{
	AGameField,
};